# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'testServiceConnection'
    subscriptionId: 'd0b3a88d-9598-4100-a5e6-cf33d1eda50f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'scosticRG'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/scostic/testRepo/main/CreateVM/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployLinuxVM'
    overrideParameters: -vmName ubuntu-little

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
